stages:
- stage: build
  jobs:
    - job: build_av
      displayName: 'Build and Push Docker image'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - script: |
            echo $(DOCKER_TOKEN) | docker login -u $(DOCKER_USER) --password-stdin
            docker build --no-cache -t $(DOCKER_USER)/alpha-visa:FE .
            docker push $(DOCKER_USER)/alpha-visa:FE
# - stage: deploy
#   jobs:
#     - job: deploy_av
#       displayName: 'Deploy Docker image'
#       pool:
#         name: Default
#       steps:
#         - task: Bash@3
#           inputs:
#             targetType: 'inline'
#             script: |
#               docker pull $(DOCKER_USER)/alpha-visa:FE
#               docker stop alpha-visa_FE
#               docker rm alpha-visa_FE
#               docker-compose -f /home/ubuntu/side-projects/alpha-visa/docker-compose.yaml up -d
#               docker builder prune --force && docker image prune --force
